import * as vscode from "vscode";
import { SidebarMessage } from "../../types/sidebarMessage";
import { APIService } from "../../services/APIService";
import { WorkspaceService } from "../../services/workspaceService";
import { GitService } from "../../services/gitService";
import { waitUntil } from "../../utils/wait";

export class ProjectIndexingHandler {

    private readonly apiService = new APIService();
    private readonly workspaceService = new WorkspaceService();
    private readonly gitService = new GitService();

    constructor(
        private readonly view: vscode.WebviewView        
    ) {}

    public async handle(message: SidebarMessage) {
        await this.gitService.initialize();
        console.log(message.command);

        const projectId = vscode.workspace.getConfiguration("vision").get<string>("projectId") 
            || this.workspaceService.getWorkspace()?.name 
            || "None";
        
            const repo = await this.gitService.getRepositoryInfo();
        const remote = repo?.remote; 
        const branch = repo?.branch;

        const body = {
            remote: remote,
            project_id: projectId,
            branch: branch,
            profile: {
                chunker: "ast-v3",
                context_header: true,
                use_bm25: true
            },
            briefing: true,
            model: vscode.workspace.getConfiguration("vision").get("modelId"),
            note: `${projectId} generated by Vision Extension`
        };
        console.log(body);
        try {
            const response: any = await this.apiService.post("/index", body, 60 * 1000);
            if (!response) {
                throw new Error("서버가 응답하지 않습니다.");
            }
            const state = await response.state;
            if (state === "done") {
                vscode.window.showInformationMessage("프로젝트 인덱싱이 완료되었습니다.");
                this.view.webview.postMessage({
                    command: "indexingDone"
                });
            } else if (state === "running") {
                this.view.webview.postMessage({
                    command: "indexingRunning"
                });
                vscode.window.showInformationMessage("프로젝트 인덱싱이 진행 중입니다.");
                waitUntil(async () => await this.isIndexed(this.view, projectId), 10 * 60 * 1000, 100)
                    .then(async (indexed) => {
                        if (!indexed) {
                            const rsp: any = await this.apiService.get(`/index/status?project_id=${projectId}`);
                            const error = rsp.error;
                            vscode.window.showErrorMessage("프로젝트 인덱싱이 실패했습니다: " + (error?.message || error || 'Unknown error'));
                            this.view.webview.postMessage({
                                command: "indexingError",
                                data: error?.message || error || "Server Error"
                            });
                            return;
                        }
                        vscode.window.showInformationMessage("프로젝트 인덱싱이 완료되었습니다.");
                        this.view.webview.postMessage({
                            command: "indexingDone"
                        });
                    })
                    .catch(() => {
                        throw new Error("프로젝트 인덱싱 중 오류가 발생했습니다.");
                    });
                waitUntil(async () => await this.isBriefReady(projectId), 10 * 60 * 1000, 30 * 1000)
                    .then((briefReady) => {
                        if (!briefReady) {
                            vscode.window.showErrorMessage("프로젝트 브리핑이 시간 내에 준비되지 않았습니다.");
                            this.view.webview.postMessage({
                                command: "briefStatus",
                                data: false
                            });
                            return;
                        }
                        vscode.window.showInformationMessage("프로젝트 브리핑이 준비되었습니다.");
                        this.view.webview.postMessage({
                            command: "briefStatus",
                            data: true
                        });
                    })
                    .catch(() => {
                        vscode.window.showErrorMessage("프로젝트 브리핑 상태 확인 중 오류가 발생했습니다.");
                        this.view.webview.postMessage({
                            command: "briefStatus",
                            data: false
                        });
                    });
            } else {
                throw new Error(response.error || "Unknown error occurred during project indexing.");
            }
        } catch (error) {
            console.error(error);
            vscode.window.showErrorMessage(`프로젝트 인덱싱 중 오류가 발생했습니다. ${error}`);
            this.view.webview.postMessage({
                command: "indexingError",
                data: error || "Unknown error occurred during project indexing."
            });
        }        
    }

    private async isIndexed(
        view: vscode.WebviewView, 
        projectId: string | undefined
    ): Promise<Boolean | undefined> {
        try {
            const response: any = await this.apiService.get(
                `/index/status?project_id=${projectId}`
            );
            const state = response.state;
            console.log("indexing status: ", state);
            switch (state) {
                case "running":
                    const rate = response.total > 0 ? response.processed / response.total : 0;
                    view.webview.postMessage({
                        command: "indexingStatus",
                        data: rate
                    });
                    return undefined;
                case "done":
                    return true;
                case "failed":
                    return false;
                default:
                    return undefined;
            }
        } catch (error) {
            return undefined;
        }
    }

    
    private async isBriefReady(projectId: string | undefined): Promise<Boolean | undefined> {
        try {
            const response:any = await this.apiService.get(
                `/briefing?project_id=${projectId}`
            );
            const returnValue = response.ok && response.briefing !== "";
            return returnValue ? true : undefined;
        } catch (error) {
            return undefined;
        }
    }
}