import * as vscode from "vscode";
import { SidebarMessage } from "../../types/sidebarMessage";
import { APIService } from "../../services/APIService";
import { WorkspaceService } from "../../services/workspaceService";
import { GitService } from "../../services/gitService";
import { waitUntil } from "../../utils/wait";

export class ProjectIndexingHandler {

    private readonly apiService = new APIService();
    private readonly workspaceService = new WorkspaceService();
    private readonly gitService = new GitService();

    constructor(
        private readonly view: vscode.WebviewView        
    ) {}

    public async handle(message: SidebarMessage) {
        await this.gitService.initialize();
        console.log(message.command);
        const projectName = this.workspaceService.getWorkspace()?.name;
        const repo = await this.gitService.getRepositoryInfo();
        const remote = repo?.remote; 

        vscode.window.showInformationMessage("서버에 인덱싱 요청을 보냈습니다.");
        const body = {
            remote: remote,
            project_id: projectName,
            profile: {
                chunker: "ast-v2",
                context_header: true,
                use_bm25: true
            },
            briefing: true,
            model: vscode.workspace.getConfiguration("vision").get("model"),
            note: `${projectName} generated by Vision Extension`
        };
        try {
            const response: any = await this.apiService.post("/index", body, 60 * 1000);
            const state = await response.state;
            if (state === "done") {
                vscode.window.showInformationMessage("프로젝트 인덱싱이 완료되었습니다.");
                this.view.webview.postMessage({
                    command: "indexingDone"
                });
            } else if (state === "running") {
                vscode.window.showInformationMessage("프로젝트 인덱싱이 진행 중입니다.");
                waitUntil(async () => await this.isIndexed(projectName), 30 * 1000, 10 * 60 * 1000)
                    .then(() => {
                        vscode.window.showInformationMessage("프로젝트 인덱싱이 완료되었습니다.");
                        this.view.webview.postMessage({
                            command: "indexingDone"
                        });
                    })
                    .catch(() => {
                        vscode.window.showErrorMessage("프로젝트 인덱싱이 시간 내에 완료되지 않았습니다.");
                        this.view.webview.postMessage({
                            command: "indexingError"
                        });
                    });
                waitUntil(async () => await this.isBriefReady(projectName), 30 * 1000, 10 * 60 * 1000)
                    .then(() => {
                        vscode.window.showInformationMessage("프로젝트 브리핑이 준비되었습니다.");
                        this.view.webview.postMessage({
                            command: "briefStatus", 
                            data: true
                        });
                    })
                    .catch(() => {
                        vscode.window.showErrorMessage("프로젝트 브리핑이 시간 내에 준비되지 않았습니다.");
                        this.view.webview.postMessage({
                            command: "briefStatus", 
                            data: false
                        });
                    });
            } else {
                throw new Error(response.error || "Unknown error occurred during project indexing.");
            }
        } catch (error) {
            console.error(error);
            vscode.window.showErrorMessage(`프로젝트 인덱싱 중 오류가 발생했습니다. ${error}`);
            this.view.webview.postMessage({
                command: "indexingError"
            });
        }        
    }

    private async isIndexed(projectName: string | undefined): Promise<Boolean | undefined> {
        try {
            const response: any = await this.apiService.get(`/index/exists?project_id=${projectName}`);
            const returnValue = response.exists ? true : undefined;
            return returnValue;
        } catch (error) {
            return undefined;
        }
    }

    
    private async isBriefReady(projectName: string | undefined): Promise<Boolean | undefined> {
        try {
            const response:any = await this.apiService.get(
                `/briefing?project_id=${projectName}`
            );
            const returnValue = response.ok && response.briefing !== "";
            return returnValue ? true : undefined;
        } catch (error) {
            return undefined;
        }
    }
}